#!/bin/bash -eux

MYSQL_ROOT_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`
NEXTCLOUD_ADMIN_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

var=$(for folder in `ls /data/domains`; do cat /data/domains/$folder/.env | grep SUBNET | cut -d"=" -f2; done | sort | tail -n1)
SUBNET=$(($var +1))

echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > .env
echo "MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
echo "NEXTCLOUD_ADMIN_PASSWORD={NEXTCLOUD_ADMIN_PASSWORD}" >> .env
echo "SUBNET=${SUBNET}" >> .env

cat > mail.config.php <<EOF
<?php
\$CONFIG = array (
  'mail_domain' => '${MAIL_DOMAIN}',
  'mail_from_address' => 'noreply.${URL}',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '${MAIL_HOST}',
  'mail_smtpport' => '${MAIL_PORT}',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'noreply.${URL}@${MAIL_DOMAIN}',
  'mail_smtppassword' => '${MAIL_PASS}',
  'mail_smtpsecure' => 'tls',
);
EOF


