#!/bin/bash -eux

MYSQL_ROOT_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

var=$(for folder in `ls /data/domains`; do cat /data/domains/$folder/.env | grep SUBNET | cut -d"=" -f2; done | sort | tail -n1)
SUBNET=$(($var +1))

echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > .env
echo "MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
echo "SUBNET=${SUBNET}" >> .env
echo "MAIL_DOMAIN=${MAIL_DOMAIN}" >> .env
echo "URL=${URL}" >> .env
echo "MAIL_HOST=${MAIL_HOST}" >> .env
echo "MAIL_PORT=${MAIL_PORT}" >> .env
echo "MAIL_PASS=${MAIL_PASS}" >> .env
echo "MAIL_FROM=noreply.${URL}" >> .env
echo "SMTP_NAME=noreply.${URL}@${MAIL_DOMAIN} >> .env


